### ISSUE TITLE
iCloud for Windows intigration stopped working with latest version 15.3.146.0

### ISSUE THREAD

**Issue by gamertrumpfi** [au2001/icloud-passwords-firefox#56]
I was just installing some Windows & Windows store updates and after a restart this great tool stopped working.
I tried getting the new listing as well with also the latest .exe but this setup seams not to work as either. cleaning firefox and also a reinstall of firefox and the plugins didnt work.
It would be great if someone could get it to work again.

**Comment by stKeyPoints** [comment]
same problem

**Comment by muleyo** [comment]
I got the same issue. I fixed it for myself by installing a previous version.

You can download a previous version from here: <REDACTED>

PS: Make sure to disable Auto-Updates in the Microsoft Store for now after you've installed a previous version.

**Comment by HarryDymond** [comment]
Installing the earlier version of iCloud did not fix the issue for me. Clicking on the extension in Firefox still shows the message "Error - This Extension requires iCloud for Windows to be installed"

**Comment by au2001** [comment]
> You can download a previous version from here:

@muleyo Please refrain from posting unofficial links.
While downloading a previous version can solve the issue, I only recommend it for users who know what they're doing.
Downloading a malicious .exe could steal all your passwords, and even official outdated versions could have security issues.

I will investigate the issue on the latest iCloud for Windows version and provide an update here.

**Comment by dxnnie** [comment]
@au2001 the new update not only works, but it's also faster. Thanks a lot. 
Windows 11 (24H2 - 26100.3775) +  Firefox 137.0.2

**Comment by gamertrumpfi** [comment]
Thanks for the hint. Just saw that there was a new release. I will test it as soon i am on my windows machine again.

**Comment by HarryDymond** [comment]
@au2001 thanks! Latest update is working for me with: iCloud for Windows 15.3.138, Windows 11 24H2 (26100.3775), Firefox 137.0.2

**Comment by m8tec** [comment]
The new release doesn't seem to fix the issue for me. 
Am I missing something or are the people here who said it's working not using the newest and problematic version of iCloud for Windows, specified in the issue title?

**Comment by HarryDymond** [comment]
> The new release doesn't seem to fix the issue for me. Am I missing something or are the people here who said it's working not using the newest and problematic version of iCloud for Windows, specified in the issue title?

@m8tec I believed that I was using the latest version of iCloud, but now going back over this thread I see that 15.3.146 was the problem version, and my iCloud is still saying 15.3.138 despite me uninstalling iCloud completely and then reinstalling from the Microsoft Store. Maybe Apple pulled 15.3.146?

You can see in my previous post my current iCloud, Windows, and Firefox version numbers. I _had_ tried, before the latest version of the Firefox extension came out, installing an older version of iCloud, but that didn't work for me. Here is what I did since then:

1. Uninstalled the older version of iCloud
2. Reboot
3. Installed latest version of iCloud from Microsoft Store
4. Installed newest version of au's iCloud Passwords for Firefox

**Comment by m8tec** [comment]
I uninstalled the problematic iCloud version and reinstalled it from the Microsoft Store. It's saying 15.3.138 for me as well, seems like they really pulled it. Thanks a lot for figuring this out!

For everyone else having the issue that the extension doesn't work anymore, now's the time to downgrade iCloud and disable automatic downloads from the Microsoft Store!

**Comment by valsamis-d** [comment]
@m8tec @HarryDymond and others who have issues with iCloud 15.3.146 (Microsoft Store version).

I had an issue as well after updating to iCloud 15.3.146 and resolved it as as follows:

1. Exit Firefox
2. Edit `c:\Program Files\Mozilla Firefox\FirefoxPwdMgrHostApp_manifest.json`
3. In `"path":` I changed the iCloud version to 15.3.146: `"C:\\Program Files\\WindowsApps\\AppleInc.iCloud_15.3.146.0_x64__nzyj5cx40ttqa\\iCloud\\iCloudPasswordsExtensionHelper.exe",`

Hope this helps
Dimi

**Comment by gamertrumpfi** [comment]
Thanks i will try that.

**Comment by gamertrumpfi** [comment]
Thank you so much @au2001 @valsamis-d. The update in combination with the hint solved the issue for me.
I will mark the bug as closed :)

> [@m8tec](https://github.com/m8tec) [@HarryDymond](https://github.com/HarryDymond) and others who have issues with iCloud 15.3.146 (Microsoft Store version).
> 
> I had an issue as well after updating to iCloud 15.3.146 and resolved it as as follows:
> 
>     1. Exit Firefox
> 
>     2. Edit `c:\Program Files\Mozilla Firefox\FirefoxPwdMgrHostApp_manifest.json`
> 
>     3. In `"path":` I changed the iCloud version to 15.3.146: `"C:\\Program Files\\WindowsApps\\AppleInc.iCloud_15.3.146.0_x64__nzyj5cx40ttqa\\iCloud\\iCloudPasswordsExtensionHelper.exe",`
> 
> 
> Hope this helps Dimi

**Comment by Mettbrot** [comment]
Thank you all for this! I just tried reinstalling from 15.3.146 and it seems Apple has released a new Version to the Store (**15.3.152**) which **also works fine** when editing the manifest.json in the Firefox directory.

**Comment by dcip3** [comment]
again same problem after 15.3.152.0 icloud update(

**Comment by plungarini** [comment]
Same problem here. I've iCloud version 15.4.210 and i could not make it work in any browser, even with the official Extension. I installed the latest version via Firefox and also tried with the github release, nothing.
